radius-manager/app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, TextAreaField, SubmitField, SelectField, PasswordField, BooleanField
from wtforms.validators import DataRequired, IPAddress, NumberRange, DataRequired, Email, EqualTo


class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField('Repeat Password', validators=[DataRequired(), EqualTo('password')])
    is_admin = BooleanField('Make Admin')
    submit = SubmitField('Register')

class SwitchForm(FlaskForm):
    name = StringField('Switch Name', validators=[DataRequired()])
    ip_address = StringField('IP Address', validators=[DataRequired(), IPAddress()])
    secret = StringField('Secret', validators=[DataRequired()])
    description = TextAreaField('Description')
    submit = SubmitField('Submit')

class VlanForm(FlaskForm):
    vlan_id = IntegerField('VLAN ID', validators=[DataRequired(), NumberRange(min=1, max=4094)])
    name = StringField('VLAN Name', validators=[DataRequired()])
    description = TextAreaField('Description')
    submit = SubmitField('Submit')

class MacAddressForm(FlaskForm):
    mac_address = StringField('MAC Address', validators=[DataRequired()])
    vlan_id = SelectField('VLAN', coerce=int, validators=[DataRequired()])
    description = TextAreaField('Description')
    submit = SubmitField('Submit')

radius-manager/app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

radius-manager/app/main/routes.py
# Routes for managing switches, VLANs, and MAC address mappings
import time
from flask import render_template, redirect, url_for, flash, request, jsonify
from flask_login import login_required, current_user
from app import db
from app.main import bp
from app.models import User, Switch, Vlan, MacVlanMapping, RadCheck, RadReply, NasClient
from app.main.forms import SwitchForm, VlanForm, MacAddressForm, RegistrationForm
import re
#from pysnmp.hlapi.asyncio import getCmd
from pysnmp.hlapi.asyncio import getCmd, SnmpEngine, CommunityData, UdpTransportTarget, ContextData, ObjectType, ObjectIdentity

import asyncio
from pysnmp.hlapi.asyncio import SnmpEngine, CommunityData, UdpTransportTarget, ContextData, getCmd, ObjectType, ObjectIdentity

#import asyncio
from pysnmp.hlapi import SnmpEngine, nextCmd, CommunityData, UdpTransportTarget, ContextData, getCmd, ObjectType, ObjectIdentity


#from flask import render_template, redirect, url_for, flash, request
#from flask_login import login_required, current_user
#from app import db
##from app.main import bp
#from app.models import User
#from app.main.forms import RegistrationForm

@bp.route('/users/add', methods=['GET', 'POST'])
@login_required
def add_user():
    if not current_user.is_admin:
        flash('You do not have permission to add users.', 'danger')
        return redirect(url_for('main.index'))

    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        
        # Assign admin role if specified
        user.is_admin = form.is_admin.data

        db.session.add(user)
        db.session.commit()
        flash(f'User {user.username} has been added.', 'success')
        return redirect(url_for('main.index'))
    
    return render_template('main/add_user.html', title='Add User', form=form)

@bp.route('/')
@bp.route('/index')
@login_required
def index():
    switches = Switch.query.all()
    return render_template('main/index.html', title='Home', switches=switches)

@bp.route('/switches')
@login_required
def switches():
    switches = Switch.query.all()
    
    for switch in switches:
        print(switch.ip_address);#time.sleep(300)
        #switch.is_online = is_switch_online_snmp(switch.ip_address)
        if 1==1: #try:
            switch.is_online = is_switch_online_snmp(switch.ip_address)
            print("switch.is_online: ", switch.is_online)
        else: #except:
            pass
    return render_template('main/switches.html', title='Switches', switches=switches)


@bp.route('/switch/add', methods=['GET', 'POST'])
@login_required
def add_switch():
    form = SwitchForm()
    if form.validate_on_submit():
        switch = Switch(
            name=form.name.data,
            ip_address=form.ip_address.data,
            secret=form.secret.data,
            description=form.description.data
        )
        # Also add to the NAS table for FreeRADIUS
        nas = NasClient(
            nasname=form.ip_address.data,
            shortname=form.name.data,
            type='cisco',
            secret=form.secret.data,
            description=form.description.data
        )
        db.session.add(switch)
        db.session.add(nas)
        db.session.commit()
        flash(f'Switch {form.name.data} has been added.')
        return redirect(url_for('main.switches'))
    return render_template('main/switch_form.html', title='Add Switch', form=form)

@bp.route('/switch/<int:id>/edit', methods=['GET', 'POST'])
@login_required
def edit_switch(id):
    switch = Switch.query.get_or_404(id)
    form = SwitchForm(obj=switch)
    if form.validate_on_submit():
        switch.name = form.name.data
        switch.ip_address = form.ip_address.data
        switch.secret = form.secret.data
        switch.description = form.description.data
        # Update NAS entry
        nas = NasClient.query.filter_by(nasname=switch.ip_address).first()
        if nas:
            nas.nasname = form.ip_address.data
            nas.shortname = form.name.data
            nas.secret = form.secret.data
            nas.description = form.description.data
        db.session.commit()
        flash(f'Switch {switch.name} has been updated.')
        return redirect(url_for('main.switches'))
    return render_template('main/switch_form.html', title='Edit Switch', form=form)

@bp.route('/switch/<int:id>/delete', methods=['POST'])
@login_required
def delete_switch(id):
    switch = Switch.query.get_or_404(id)
    nas = NasClient.query.filter_by(nasname=switch.ip_address).first()
    if nas:
        db.session.delete(nas)
    db.session.delete(switch)
    db.session.commit()
    flash(f'Switch {switch.name} has been deleted.')
    return redirect(url_for('main.switches'))

@bp.route('/switch/<int:id>/vlans')
@login_required
def switch_vlans(id):
    switch = Switch.query.get_or_404(id)
    vlans = Vlan.query.filter_by(switch_id=id).all()
    return render_template('main/vlans.html', title=f'VLANs for {switch.name}', switch=switch, vlans=vlans)

@bp.route('/switch/<int:id>/vlan/add', methods=['GET', 'POST'])
@login_required
def add_vlan(id):
    switch = Switch.query.get_or_404(id)
    form = VlanForm()
    if form.validate_on_submit():
        vlan = Vlan(
            switch_id=switch.id,
            vlan_id=form.vlan_id.data,
            name=form.name.data,
            description=form.description.data
        )
        db.session.add(vlan)
        db.session.commit()
        flash(f'VLAN {form.vlan_id.data} has been added to {switch.name}.')
        return redirect(url_for('main.switch_vlans', id=switch.id))
    return render_template('main/vlan_form.html', title=f'Add VLAN to {switch.name}', form=form, switch=switch)

@bp.route('/vlan/<int:id>/edit', methods=['GET', 'POST'])
@login_required
def edit_vlan(id):
    vlan = Vlan.query.get_or_404(id)
    form = VlanForm(obj=vlan)
    if form.validate_on_submit():
        vlan.vlan_id = form.vlan_id.data
        vlan.name = form.name.data
        vlan.description = form.description.data
        db.session.commit()
        flash(f'VLAN {vlan.vlan_id} has been updated.')
        return redirect(url_for('main.switch_vlans', id=vlan.switch_id))
    return render_template('main/vlan_form.html', title=f'Edit VLAN', form=form, switch=vlan.switch)

@bp.route('/vlan/<int:id>/delete', methods=['POST'])
@login_required
def delete_vlan(id):
    vlan = Vlan.query.get_or_404(id)
    switch_id = vlan.switch_id
    db.session.delete(vlan)
    db.session.commit()
    flash(f'VLAN {vlan.vlan_id} has been deleted.')
    return redirect(url_for('main.switch_vlans', id=switch_id))

@bp.route('/switch/<int:id>/macs')
@login_required
def switch_macs(id):
    switch = Switch.query.get_or_404(id)
    mac_mappings = MacVlanMapping.query.filter_by(switch_id=id).all()
    return render_template('main/macs.html', title=f'MAC Addresses for {switch.name}', switch=switch, mac_mappings=mac_mappings)

@bp.route('/switch/<int:id>/mac/add', methods=['GET', 'POST'])
@login_required
def add_mac(id):
    switch = Switch.query.get_or_404(id)
    form = MacAddressForm()
    # Populate VLAN choices
    form.vlan_id.choices = [(v.id, f'{v.vlan_id} - {v.name}') for v in Vlan.query.filter_by(switch_id=id).order_by(Vlan.vlan_id).all()]
    if form.validate_on_submit():
        mac = normalize_mac(form.mac_address.data)
        mac_radius = mac.replace(':', '').lower()
        existing = MacVlanMapping.query.filter_by(mac_address=mac, switch_id=switch.id).first()
        if existing:
            flash(f'MAC address {mac} already exists for this switch.')
            return redirect(url_for('main.switch_macs', id=switch.id))
        vlan = Vlan.query.get(form.vlan_id.data)
        mapping = MacVlanMapping(
            mac_address=mac,
            vlan_id=vlan.id,
            switch_id=switch.id,
            description=form.description.data
        )
        radcheck = RadCheck(
            username=mac_radius,
            attribute='Auth-Type',
            op=':=',
            value='Accept'
        )
        vlan_type = RadReply(
            username=mac_radius,
            attribute='Tunnel-Type',
            op=':=',
            value='13'
        )
        vlan_medium = RadReply(
            username=mac_radius,
            attribute='Tunnel-Medium-Type',
            op=':=',
            value='6'
        )
        vlan_id = RadReply(
            username=mac_radius,
            attribute='Tunnel-Private-Group-ID',
            op=':=',
            value=str(vlan.vlan_id)
        )
        db.session.add_all([mapping, radcheck, vlan_type, vlan_medium, vlan_id])
        db.session.commit()
        flash(f'MAC address {mac} has been added to VLAN {vlan.vlan_id}.')
        return redirect(url_for('main.switch_macs', id=switch.id))
    return render_template('main/mac_form.html', title=f'Add MAC Address to {switch.name}', form=form, switch=switch)

@bp.route('/mac/<int:id>/edit', methods=['GET', 'POST'])
@login_required
def edit_mac(id):
    mapping = MacVlanMapping.query.get_or_404(id)
    form = MacAddressForm(obj=mapping)
    # Populate VLAN choices
    form.vlan_id.choices = [(v.id, f'{v.vlan_id} - {v.name}') for v in Vlan.query.filter_by(switch_id=mapping.switch_id).order_by(Vlan.vlan_id).all()]
    if form.validate_on_submit():
        mac = normalize_mac(form.mac_address.data)
        mac_radius = mac.replace(':', '').lower()
        old_mac_radius = mapping.mac_address.replace(':', '').lower()
        vlan = Vlan.query.get(form.vlan_id.data)
        mapping.mac_address = mac
        mapping.vlan_id = vlan.id
        mapping.description = form.description.data
        if mac_radius != old_mac_radius:
            RadCheck.query.filter_by(username=old_mac_radius).delete()
            RadReply.query.filter_by(username=old_mac_radius).delete()
            radcheck = RadCheck(
                username=mac_radius,
                attribute='Auth-Type',

radius-manager/app/templates/main/add_user.html
{% extends "base.html" %}

{% block content %}
<h2>Add User</h2>
<form method="POST">
    {{ form.hidden_tag() }}
    <p>{{ form.username.label }} {{ form.username() }}</p>
    <p>{{ form.email.label }} {{ form.email() }}</p>
    <p>{{ form.password.label }} {{ form.password() }}</p>
    <p>{{ form.password2.label }} {{ form.password2() }}</p>
    <p>{{ form.is_admin.label }} {{ form.is_admin() }}</p>
    <p>{{ form.submit() }}</p>
</form>
{% endblock %}

radius-manager/app/templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Dashboard: VLANager{% endblock %}</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
        <link rel="apple-touch-icon" sizes="57x57" href="{{ url_for('static', filename='images/favicon/apple-icon-57x57.png') }}">
        <link rel="apple-touch-icon" sizes="60x60" href="{{ url_for('static', filename='images/favicon/apple-icon-60x60.png') }}">
        <link rel="apple-touch-icon" sizes="72x72" href="{{ url_for('static', filename='images/favicon/apple-icon-72x72.png') }}">
        <link rel="apple-touch-icon" sizes="76x76" href="{{ url_for('static', filename='images/favicon/apple-icon-76x76.png') }}">
        <link rel="apple-touch-icon" sizes="114x114" href="{{ url_for('static', filename='images/favicon/apple-icon-114x114.png') }}">
        <link rel="apple-touch-icon" sizes="120x120" href="{{ url_for('static', filename='images/favicon/apple-icon-120x120.png') }}">
        <link rel="apple-touch-icon" sizes="144x144" href="{{ url_for('static', filename='images/favicon/apple-icon-144x144.png') }}">
        <link rel="apple-touch-icon" sizes="152x152" href="{{ url_for('static', filename='images/favicon/apple-icon-152x152.png') }}">
        <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='images/favicon/apple-icon-180x180.png') }}">
        <link rel="icon" type="image/png" sizes="192x192"  href="{{ url_for('static', filename='images/favicon/android-icon-192x192.png') }}">
        <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='images/favicon/favicon-32x32.png') }}">
        <link rel="icon" type="image/png" sizes="96x96" href="{{ url_for('static', filename='images/favicon/favicon-96x96.png') }}">
        <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='images/favicon/favicon-16x16.png') }}">
        <link rel="manifest" href="{{ url_for('static', filename='images/favicon/manifest.json') }}">
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="msapplication-TileImage" content="{{ url_for('static', filename='images/favicon/ms-icon-144x144.png') }}">
        <meta name="theme-color" content="#ffffff">
    {% endblock %}
</head>
<body>
    <header>
        <nav>
          <a href="{{ url_for('main.index') }}" class="brand">
            <img src="{{ url_for('static', filename='images/vlanager.png') }}" width="70px" alt="VLANager Logo"> VLANager
          </a>
          <ul>
            <li><a href="{{ url_for('main.switches') }}">Manage Switches</a> </a></li>
            <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
         </ul>
        </nav>
    </header>
        
<div class="container">
    {% block content_mast %}<p>Welcome, {{ current_user.username }}!</p>{% endblock %}
    {% block content %}{% endblock %}
</div>

<footer>
  <p>&copy; {{ current_year or "2025" }} VLANager. All rights reserved.</p>
</footer>
</body>
</html>

radius-manager/app/templates/main/mac_form.html
{% extends "main/index.html" %}
{% block title %}Add MAC Address: VLANager{% endblock %}
{% block content_mast %} <h2 class="mb-3">Add MAC Addresses</h2>{% endblock %}
{% block content %}
<div class="container mt-4">
    <form method="post" class="needs-validation" novalidate id="macForm">
        {{ form.hidden_tag() }}
        
        <div class="mb-3">
            {{ form.mac_address.label(class="form-label") }}
            {{ form.mac_address(class="form-control", size=20) }}
            {% if form.mac_address.errors %}
                <div class="text-danger">
                    {% for error in form.mac_address.errors %}
                        <small>{{ error }}</small>
                    {% endfor %}
                </div>
            {% endif %}
        </div>

        <div class="mb-3">
            {{ form.vlan_id.label(class="form-label") }}
            {{ form.vlan_id(class="form-control") }}
            {% if form.vlan_id.errors %}
                <div class="text-danger">
                    {% for error in form.vlan_id.errors %}
                        <small>{{ error }}</small>
                    {% endfor %}
                </div>
            {% endif %}
        </div>

        <div class="mb-3">
            {{ form.description.label(class="form-label") }}
            {{ form.description(class="form-control") }}
            {% if form.description.errors %}
                <div class="text-danger">
                    {% for error in form.description.errors %}
                        <small>{{ error }}</small>
                    {% endfor %}
                </div>
            {% endif %}
        </div>

        <!-- Submit Button with Loading Indicator -->
        <button type="submit" class="btn btn-success" id="submitButton">
            <span id="submitText">Save MAC Address</span>
            <span id="loadingSpinner" class="spinner-border spinner-border-sm d-none" role="status" aria-hidden="true"></span>
        </button>

        <!-- Back Button with Icon -->
        <a href="{{ url_for('main.switch_macs', id=switch.id) }}" class="btn btn-outline-secondary ms-2">
            <i class="fas fa-arrow-left"></i> Back to MAC List
        </a>
    </form>
</div>

<!-- JavaScript for Submit Button Feedback -->
<script>
    document.getElementById("macForm").addEventListener("submit", function() {
        let submitButton = document.getElementById("submitButton");
        document.getElementById("submitText").textContent = "Saving...";
        document.getElementById("loadingSpinner").classList.remove("d-none");
        submitButton.disabled = true;
    });
</script>
{% endblock %}

radius-manager/app/templates/main/macs.html
{% extends "main/index.html" %}
{% block title %}MAC Addresses: VLANager{% endblock %}
{% block content_mast %} <h2 class="mb-4">MAC Addresses for <strong>{{ switch.name }}</strong></h2> {% endblock %}
{% block content %}
<div class="container mt-4">
    
    

    {% if mac_mappings %}
    <table class="table table-striped table-bordered">
        <thead class="table-dark">
            <tr>
                <th>MAC Address</th>
                <th>VLAN ID</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for mapping in mac_mappings %}
            <tr>
                <td>{{ mapping.mac_address }}</td>
                <td>{{ mapping.vlan_id }}</td>
                <td>
                    <!-- Edit Button -->
                    <a href="{{ url_for('main.edit_mac', id=mapping.id) }}" class="btn btn-warning btn-sm">
                        <i class="fas fa-edit"></i> Edit
                    </a>
                    
                    <!-- Delete Form with Confirmation -->
                    <form action="{{ url_for('main.delete_mac', id=mapping.id) }}" method="post" class="d-inline" onsubmit="return confirmDelete();">
                        <button type="submit" class="btn btn-danger btn-sm">
                            <i class="fas fa-trash"></i> Delete
                        </button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <div class="alert alert-info">No MAC addresses found for this switch.</div>
    {% endif %}

    <!-- Action Buttons -->
    <a href="{{ url_for('main.add_mac', id=switch.id) }}" class="btn btn-success">
        <i class="fas fa-plus"></i> Add New MAC Address
    </a>
    
    <a href="{{ url_for('main.switches') }}" class="btn btn-outline-secondary">
        <i class="fas fa-arrow-left"></i> Back to Switches
    </a>
</div>

<!-- JavaScript for Delete Confirmation -->
<script>
    function confirmDelete() {
        return confirm("Are you sure you want to delete this MAC address?");
    }
</script>
{% endblock %}

radius-manager/app/templates/main/switch_form.html
{% extends "main/index.html" %}
{% block title %}Add Switch: VLANager{% endblock %}
{% block content_mast %}
<h2 class="mb-4">Add Switch</h2>{% endblock %}
{% block content %}
<div class="container mt-4">

    <form method="post" class="needs-validation" novalidate>
        {{ form.hidden_tag() }}

        <div class="mb-3">
            {{ form.name.label(class="form-label") }}
            {{ form.name(class="form-control", size=32) }}
        </div>

        <div class="mb-3">
            {{ form.ip_address.label(class="form-label") }}
            {{ form.ip_address(class="form-control", size=32) }}
        </div>

        <div class="mb-3">
            {{ form.secret.label(class="form-label") }}
            {{ form.secret(class="form-control", size=32) }}
        </div>

        <div class="mb-3">
            {{ form.description.label(class="form-label") }}
            {{ form.description(class="form-control") }}
        </div>

        <div class="d-flex gap-2">
            <button type="submit" class="btn btn-success">
                <i class="fas fa-save"></i> Save Switch
            </button>
            <a href="{{ url_for('main.switches') }}" class="btn btn-secondary">
                <i class="fas fa-arrow-left"></i> Back to Switches
            </a>
        </div>
    </form>
</div>
{% endblock %}

radius-manager/app/templates/main/switches.html
{% extends "main/index.html" %}
{% block title %}Switches: VLANager{% endblock %}
{% block content_mast %}<h2 class="mb-3">Switches</h2>{% endblock %}
{% block content %}
<div class="container mt-4">
    

    {% if switches %}
    <table class="table table-striped table-bordered">
        <thead class="table-dark">
            <tr>
                <th>Name</th>
                <th>IP Address</th>
                <th>Actions</th>
                <th>Status</t>
            </tr>
        </thead>
        <tbody>
            {% for switch in switches %}
            <tr>
                <td>{{ switch.name }}</td>
                <td>{{ switch.ip_address }}</td>
                <td>
                    <!-- Edit Button -->
                    <a href="{{ url_for('main.edit_switch', id=switch.id) }}" class="btn btn-warning btn-sm">
                        <i class="fas fa-edit"></i> Edit
                    </a>

                    <!-- Delete Form with Confirmation -->
                    <form action="{{ url_for('main.delete_switch', id=switch.id) }}" method="post" class="d-inline" onsubmit="return confirmDelete();">
                        <button type="submit" class="btn btn-danger btn-sm">
                            <i class="fas fa-trash"></i> Delete
                        </button>
                    </form>

                    <!-- VLAN & MAC Address Links -->
                    <a href="{{ url_for('main.switch_vlans', id=switch.id) }}" class="btn btn-info btn-sm">
                        <i class="fas fa-network-wired"></i> VLANs
                    </a>
                    <a href="{{ url_for('main.switch_macs', id=switch.id) }}" class="btn btn-primary btn-sm">
                        <i class="fas fa-list"></i> MAC Addresses
                    </a>
                </td>
                <td>
                    {% if switch.is_online %}
                        <span class="badge bg-success">Online</span>
                    {% else %}
                        <span class="badge bg-danger">Offline</span>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <div class="alert alert-info">No switches found.</div>
    {% endif %}

    <!-- Add New Switch Button -->
    <a href="{{ url_for('main.add_switch') }}" class="btn btn-success">
        <i class="fas fa-plus"></i> Add New Switch
    </a>
</div>

<!-- JavaScript for Delete Confirmation -->
<script>
    function confirmDelete() {
        return confirm("Are you sure you want to delete this switch?");
    }
</script>
{% endblock %}

radius-manager/app/templates/main/vlan_form.html
{% extends "main/index.html" %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4">{{ title }}</h2>

    <form method="post" class="needs-validation" novalidate>
        {{ form.hidden_tag() }}

        <div class="mb-3">
            {{ form.vlan_id.label(class="form-label") }}
            {{ form.vlan_id(class="form-control", size=5, placeholder="Enter VLAN ID") }}
        </div>

        <div class="mb-3">
            {{ form.name.label(class="form-label") }}
            {{ form.name(class="form-control", size=32, placeholder="Enter VLAN name") }}
        </div>

        <div class="mb-3">
            {{ form.description.label(class="form-label") }}
            {{ form.description(class="form-control", rows=3, placeholder="Enter VLAN description") }}
        </div>

        <button type="submit" class="btn btn-primary">{{ form.submit.label.text }}</button>
        <a href="{{ url_for('main.switch_vlans', id=switch.id) }}" class="btn btn-secondary">Back to VLANs</a>
    </form>
</div>
{% endblock %}

radius-manager/app/templates/main/vlans.html
{% extends "main/index.html" %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4">VLANs for {{ switch.name }}</h2>

    {% if vlans %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>VLAN ID</th>
                <th>Name</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for vlan in vlans %}
            <tr>
                <td>VLAN {{ vlan.vlan_id }}</td>
                <td>{{ vlan.name }}</td>
                <td>
                    <a href="{{ url_for('main.edit_vlan', id=vlan.id) }}" class="btn btn-sm btn-warning">Edit</a>
                    <form action="{{ url_for('main.delete_vlan', id=vlan.id) }}" method="post" style="display:inline;">
                        <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure you want to delete VLAN {{ vlan.vlan_id }}?');">
                            Delete
                        </button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>No VLANs found for this switch.</p>
    {% endif %}

    <div class="mt-3">
        <a href="{{ url_for('main.add_vlan', id=switch.id) }}" class="btn btn-primary">Add New VLAN</a>
        <a href="{{ url_for('main.switches') }}" class="btn btn-secondary">Back to Switches</a>
    </div>
</div>
{% endblock %}